# Generated by Django 3.0.3 on 2020-03-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vksdk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyboards',
            name='name',
            field=models.CharField(default='hello', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
