# Generated by Django 3.0.3 on 2020-03-22 00:57

from django.db import migrations, models
import vksdk.models


class Migration(migrations.Migration):

    dependencies = [
        ('vksdk', '0002_keyboards_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('carousel', vksdk.models.PickleField()),
            ],
        ),
    ]
